version: '3.2'
services:
  cucumber-results-react:
    build:
      context: ../cucumber-test-results-react
      dockerfile: Dockerfile
    command: bash -c "/usr/share/nginx/html/env.sh && envsubst '$${BACKEND_URL} $${TESTBENCH_NUMBER}' </etc/nginx/conf.d/nginx.conf> /etc/nginx/conf.d/nginx.conf && nginx -g \"daemon off;\""
    ports:
      - "3035:80"
    depends_on:
      - cucumber-results-spring-boot
    environment:
      - BACKEND_URL=localhost:3036
      - TESTBENCH_NUMBER=55
  cucumber-results-spring-boot:
    build:
      context: ../cucumber-test-results-spring-boot
      dockerfile: Dockerfile
    restart: always
    command: ["java",  "-jar", "/app.jar"]
    ports:
      - "3036:8080"