version: '3.2'
services:
  cucumber-results-react:
    build:
      context: ../cucumber-test-results-react
      dockerfile: Dockerfile
    command: bash -c "/usr/share/nginx/html/env.sh && envsubst '$${BACKEND_URL}' </etc/nginx/conf.d/nginx.conf> /etc/nginx/conf.d/nginx.conf && nginx -g \"daemon off;\""
    ports:
      - "3035:80"
    depends_on:
      - cucumber-results-spring-boot
    environment:
      - BACKEND_URL=localhost:3036
      - REACT_APP_TESTBENCH_NUMBER=55
      - REACT_APP_BACKEND_IP=localhost
      - REACT_APP_TB_TO_BE_OBSERVED_IP=localhost
      - REACT_APP_BACKEND_PORT=3036
      - REACT_APP_GATEWAY_PORT=3002
      - REACT_APP_JAVA_COMPUTATION_PORT=3011
      - REACT_APP_OVERLAY_KPI_PORT=3004
      - REACT_APP_AUTHENTICATION_PORT=3001
      - REACT_APP_SNAPSHOT_SERVICE_PORT=3009
      - REACT_APP_LIS_DATA_CHANNEL_PORT=3013
      - REACT_APP_SCREENSHOT_SERVICE_PORT=3012
      - REACT_APP_REACT_PORT=3000
      - REACT_APP_REACT_CA_PORT=3018
      - REACT_APP_CUSTOMER_PROJECTS_PORT=3015
      - REACT_APP_DATA_ASSOCIATION_PORT=3014
  cucumber-results-spring-boot:
    build:
      context: ../cucumber-test-results-spring-boot
      dockerfile: Dockerfile
    restart: always
    command: ["java",  "-jar", "/app.jar"]
    ports:
      - "3036:8080"