version: '3.2'
services:
  cucumber-results-react:
    image: apps-vcp-nexus.asml.com:18443/cucumber-results-react
    volumes:
      - '/usr/src/app/node_modules'
    command: npm start -p 3000 -b '0.0.0.0'
    ports:
      - "3035:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_TESTBENCH_NUMBER=${TB_NUMBER}
      - REACT_APP_BACKEND_IP=${TB_IP}
      - REACT_APP_TB_TO_BE_OBSERVED_IP=${TB_TO_BE_OBSERVED_IP}
      - REACT_APP_BACKEND_PORT=3036
      - REACT_APP_GATEWAY_PORT=3002
      - REACT_APP_JAVA_COMPUTATION_PORT=3011
      - REACT_APP_OVERLAY_KPI_PORT=3004
      - REACT_APP_AUTHENTICATION_PORT=3001
      - REACT_APP_SNAPSHOT_SERVICE_PORT=3009
      - REACT_APP_LIS_DATA_CHANNEL_PORT=3013
      - REACT_APP_SCREENSHOT_SERVICE_PORT=3012
      - REACT_APP_REACT_PORT=3000
      - REACT_APP_REACT_CA_PORT=3018
      - REACT_APP_CUSTOMER_PROJECTS_PORT=3015
    tty: true
  cucumber-results-spring-boot:
    image: apps-vcp-nexus.asml.com:18443/cucumber-results-spring-boot
    restart: always
    command: ["java",  "-jar", "/app.jar"]
    ports:
      - "3036:8080"